version: '3.4'

services:
  api:
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    build:
      context: .
      dockerfile: findox.Api/Dockerfile
    container_name: api
    ports:
      - "8002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - STORAGE_CRYPTO_KEY=MqSm0P5dMgFSZhEBKpCv4dVKgDrsgrmT
      - STORAGE_CONN_STRING=Host=db;Database=storage_db;Port=5432;Username=admin;Password=admin1234

    depends_on:
      - db
      - db-migrations
    networks:
      - app-network

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=storage_db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network
  db-migrations:
    build:
        context: "./findox.Data/migrations"
    container_name: "db-migrations"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/storage_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin1234
    volumes:
        - ./findox.Data/migrations:/flyway/sql
    networks:
        - app-network
    depends_on:
        - db
networks:
   app-network:
       driver: bridge